const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const {createRequire}=require('node:module'),{Pool}=require('pg'),{createStore}=require('../storage/postgres');
const {hashToken}=require('../auth/customers'),recovery=require('../auth/recovery'),{createEmailProvider}=require('../services/email');
const testPath=path.join(__dirname,'security-abuse.test.cjs'),source=fs.readFileSync(testPath,'utf8');
const {harness}=new Function('require','__dirname',source.slice(0,source.indexOf('test("approved prices'))+'\nreturn {harness};')(createRequire(testPath),__dirname);
const account={fullName:'Recovery Test',email:'recovery@example.test',phone:'2015550166',password:'Synthetic original passphrase'};
const newPassword='Synthetic replacement passphrase',enabled={CUSTOMER_EMAIL_RECOVERY_ENABLED:'true'};
const cookies=r=>r.headers.getSetCookie().map(x=>x.split(';')[0]).filter(x=>!x.endsWith('=')).join('; ');
const resetCookie=r=>r.headers.getSetCookie().find(x=>x.includes('er_customer_reset='))?.split(';')[0];
async function setup(t,store){const h=await harness(t,enabled,'[]',store),r=await h.request('/api/customer/register',account);assert.equal(r.status,201);return {h,session:cookies(r)};}
async function sent(h,email=account.email){const before=h.state.emailMessages.length,r=await h.request('/api/customer/recovery/request',{email});for(let i=0;i<30&&h.state.emailMessages.length===before;i++)await new Promise(r=>setImmediate(r));return r;}
const exchange=(h,token=h.state.emailMessages.at(-1)?.token)=>h.request('/api/customer/recovery/exchange',{token});
const reset=(h,grant,body={password:newPassword,confirmPassword:newPassword})=>h.request('/api/customer/recovery/reset',body,{cookie:resetCookie(grant)});

test('email recovery: generic known/unknown responses, normalization, entropy, hash-only persistence and no disclosure',async t=>{
 const {h}=await setup(t),known=await sent(h,' Recovery@EXAMPLE.TEST '),unknown=await sent(h,'unknown@example.test');assert.equal(known.status,200);assert.equal(unknown.status,200);assert.deepEqual(known.body,unknown.body);assert.equal(known.body.message,recovery.MESSAGE);
 const m=h.state.emailMessages[0];assert.equal(m.email,account.email);assert.match(m.token,/^[A-Za-z0-9_-]{43}$/);assert.equal(Buffer.from(m.token,'base64url').length,32);
 const rows=[...h.testStore.shared.recovery.values()];assert.ok(rows.every(r=>r.method==='email_link'&&r.code_verifier===null));assert.ok(rows.some(r=>r.email_token_hash===hashToken(m.token)));assert.ok(!JSON.stringify(rows).includes(m.token));
 for(const r of [known,unknown]){assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.equal(r.headers.get('set-cookie'),null);assert.ok(!JSON.stringify(r.body).includes(m.token));}assert.ok(!h.state.logs.join('').includes(m.token));
});
test('reset revokes all customer sessions/challenges; old password fails, new password works and replay fails',async t=>{
 const {h,session}=await setup(t),other=await h.request('/api/customer/login',{email:account.email,password:account.password});await sent(h);h.advance(61000);await sent(h);const grant=await exchange(h);assert.equal(grant.status,200);assert.deepEqual(grant.body,{ok:true});assert.equal((await reset(h,grant)).status,200);
 for(const cookie of [session,cookies(other)])assert.equal((await h.request('/api/customer/profile',undefined,{cookie})).status,401);
 assert.equal((await h.request('/api/customer/login',{email:account.email,password:account.password})).status,401);assert.equal((await h.request('/api/customer/login',{email:account.email,password:newPassword})).status,200);assert.equal((await exchange(h)).status,400);assert.equal((await reset(h,grant)).status,400);assert.ok([...h.testStore.shared.recovery.values()].every(r=>r.consumed_at));
});
test('ten-minute expiry is not extended by exchange; expired tokens and grants fail',async t=>{
 const {h}=await setup(t);await sent(h);h.advance(9*60000);const grant=await exchange(h);assert.equal(grant.status,200);assert.match(grant.headers.get('set-cookie'),/Max-Age=60;/);h.advance(60001);assert.equal((await reset(h,grant)).status,400);assert.equal((await exchange(h)).status,400);
});
test('concurrent exchanges are single-use; malformed/forged tokens and obsolete SMS endpoints fail',async t=>{
 const {h}=await setup(t);await sent(h);const results=await Promise.all([exchange(h),exchange(h)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);for(const token of [null,{},'bad','a'.repeat(43),crypto.randomBytes(32).toString('base64url')])assert.equal((await exchange(h,token)).status,400);assert.equal((await h.request('/api/customer/recovery/verify',{code:'000000'})).status,404);
});
test('forged browser account identifiers cannot redirect reset to another customer',async t=>{
 const {h}=await setup(t),b={...account,email:'second@example.test',phone:'2025550166'};assert.equal((await h.request('/api/customer/register',b)).status,201);await sent(h);const grant=await exchange(h);assert.equal((await reset(h,grant,{password:newPassword,confirmPassword:newPassword,email:b.email,customerId:[...h.testStore.shared.customers.values()].find(c=>c.normalized_email===b.email).id})).status,200);assert.equal((await h.request('/api/customer/login',{email:b.email,password:account.password})).status,200);
});
test('normalized email cooldown and persistent limits work across workers without invalidating existing links',async t=>{
 const {h}=await setup(t),b=await harness(t,enabled,'[]',h.testStore);await sent(h);const first=h.state.emailMessages[0].token;assert.equal((await sent(b,' RECOVERY@EXAMPLE.TEST ')).status,200);assert.equal(b.state.emailMessages.length,0);h.advance(61000);await sent(h);h.advance(61000);await sent(h);assert.equal(h.state.emailMessages.length,2);assert.equal((await exchange(h,first)).status,200);
});
test('persistent client limits and HTTP IP limits bound email spam regardless of account existence',async t=>{
 const {h}=await setup(t);for(let i=0;i<22;i++){h.advance(61000);assert.equal((await sent(h,'unknown'+i+'@example.test')).status,200);}const n=h.testStore.shared.recovery.size;h.advance(61000);await sent(h);assert.equal(h.testStore.shared.recovery.size,n);assert.equal(h.state.emailMessages.length,0);const b=await harness(t,enabled);for(let i=0;i<5;i++)assert.equal((await sent(b)).status,200);assert.equal((await sent(b)).status,429);
});
test('concurrent requests cannot bypass email cooldown across storage instances',async t=>{const {h}=await setup(t),b=await harness(t,enabled,'[]',h.testStore);await Promise.all([sent(h),sent(b),sent(h)]);assert.equal(h.state.emailMessages.length+b.state.emailMessages.length,1);});
test('malformed input, phone-only recovery, invalid passwords and cross-origin mutations fail',async t=>{
 const {h}=await setup(t);for(const email of [null,[],{},'bad','x'.repeat(255)])assert.equal((await h.request('/api/customer/recovery/request',{email})).status,400);h.advance(61000);assert.equal((await h.request('/api/customer/recovery/request',{phone:account.phone})).status,400);h.advance(61000);await sent(h);const grant=await exchange(h);for(const body of [{password:'short',confirmPassword:'short'},{password:newPassword,confirmPassword:'different'},{password:'x'.repeat(129),confirmPassword:'x'.repeat(129)}])assert.equal((await reset(h,grant,body)).status,400);for(const action of ['request','exchange','reset'])assert.equal((await h.request('/api/customer/recovery/'+action,{email:account.email},{origin:'https://attacker.example.test'})).status,403);
});
test('mock provider failure is generic; failure cannot authorize reset or leak provider diagnostics',async t=>{const {h}=await setup(t);h.state.emailFail=true;assert.equal((await sent(h)).status,200);assert.equal([...h.testStore.shared.recovery.values()][0].delivery_state,'failed');assert.equal((await exchange(h)).status,400);assert.doesNotMatch(h.state.logs.join(''),/synthetic email secret marker|recovery@example/);});
test('disabled recovery and enabled missing production configuration fail closed',async t=>{const h=await harness(t);assert.equal((await sent(h)).status,503);const b=await harness(t,{...enabled,TEST_VALIDATE_EMAIL_CONFIG:true,NODE_ENV:'production',SITE_URL:'https://er.example.test'});await new Promise(r=>setImmediate(r));assert.equal(b.state.listenCalls||0,0);assert.equal((await sent(b)).status,503);});
test('production reset cookie attributes are secure and storage failures remain generic/fail closed',async t=>{const h=await harness(t,{...enabled,NODE_ENV:'production',SITE_URL:'https://er.example.test'});await h.request('/api/customer/register',account);await sent(h);const grant=await exchange(h);for(const p of [/__Secure-er_customer_reset=/,/HttpOnly/,/Secure/,/SameSite=Strict/,/Path=\/api\/customer\/recovery/,/Max-Age=600/])assert.match(grant.headers.get('set-cookie'),p);h.storageFailures.write=true;assert.equal((await sent(h)).status,503);assert.equal((await exchange(h)).status,503);});
test('GET/scanner visits do not consume reset links and sensitive reset resources have restrictive headers',async t=>{const {h}=await setup(t);await sent(h);for(const file of ['/reset-password.html','/reset-password.js']){const r=await h.request(file);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.match(r.headers.get('content-security-policy'),/default-src 'none'/);assert.equal(r.headers.get('set-cookie'),null);assert.ok(!String(r.body).includes(h.state.emailMessages[0].token));}assert.equal((await h.request('/api/customer/recovery/exchange')).status,403);assert.equal((await exchange(h)).status,200);});
test('Resend adapter uses canonical fragment links, bounded timeouts, idempotency and no tracking resources',async()=>{
 const calls=[],p=createEmailProvider({enabled:true,apiKey:'synthetic-only-key',from:'accounts@erlimousineservice.com',siteUrl:'https://erlimousineservice.com',production:true,fetchImpl:async(url,options)=>{calls.push({url,options});return {ok:true,json(){throw new Error('must not read provider body');}};}}),token=crypto.randomBytes(32).toString('base64url');await p.sendResetLink({email:account.email,token,attemptId:'synthetic'});const c=calls[0],body=JSON.parse(c.options.body);assert.equal(c.url,'https://api.resend.com/emails');assert.ok(c.options.signal instanceof AbortSignal);assert.equal(c.options.headers['Idempotency-Key'],'customer-recovery/synthetic');assert.ok(body.text.includes('https://erlimousineservice.com/reset-password.html#token='+token));assert.ok(!body.html.includes('<img'));assert.ok(!('click_tracking' in body));assert.deepEqual(body.to,[account.email]);
});
test('Resend rejection/timeout messages are sanitized; malformed/insecure configuration never downgrades',async()=>{
 const c={enabled:true,apiKey:'synthetic-only-key',from:'accounts@erlimousineservice.com',siteUrl:'https://erlimousineservice.com',production:true};for(const fetchImpl of [async()=>({ok:false}),async()=>{throw new DOMException('synthetic secret URL','TimeoutError');}])await assert.rejects(createEmailProvider({...c,fetchImpl}).sendResetLink({email:account.email,token:'a'.repeat(43),attemptId:'synthetic'}),e=>e.message==='Email delivery unavailable.');for(const changes of [{apiKey:''},{from:'evil@example.test'},{siteUrl:'http://erlimousineservice.com'},{siteUrl:'https://user:password@erlimousineservice.com'},{siteUrl:'https://erlimousineservice.com/?token=x'},{siteUrl:'not-a-url'},{siteUrl:'https://erlimousineservice.com/path'}])assert.throws(()=>createEmailProvider({...c,...changes}),e=>e.message==='Email recovery configuration unavailable.');assert.equal(createEmailProvider({enabled:false}).enabled,false);assert.ok(createEmailProvider({...c,siteUrl:'http://localhost:3000',production:false}).enabled);
});
test('reset page strips fragment before any exchange, needs explicit action and never persists raw token',async()=>{
 const events={},els={};for(const id of ['emailResetForm','exchangeLink','resetIntro','requestAnother','resetMessage'])els[id]={hidden:false,textContent:'',addEventListener:(event,fn)=>{events[id+event]=fn;}};const token=crypto.randomBytes(32).toString('base64url'),requests=[],history=[];const c={location:{hash:'#token='+token,pathname:'/reset-password.html'},history:{replaceState:(...args)=>history.push(args)},window:{addEventListener(){}},document:{addEventListener:(event,fn)=>{events[event]=fn;},getElementById:id=>els[id]},fetch:async(url,options)=>{requests.push({url,options});return {ok:true,json:async()=>({ok:true})};}};const js=fs.readFileSync(path.join(__dirname,'../public/reset-password.js'),'utf8');vm.runInNewContext(js,c);assert.equal(history[0][2],'/reset-password.html');assert.equal(requests.length,0);events.DOMContentLoaded();assert.equal(requests.length,0);await events.exchangeLinkclick();assert.equal(requests.length,1);assert.equal(requests[0].url,'/api/customer/recovery/exchange');assert.equal(JSON.parse(requests[0].options.body).token,token);assert.equal(els.emailResetForm.hidden,false);assert.doesNotMatch(js,/localStorage|sessionStorage|console\.|document\.cookie/);assert.match(js,/finally\{token=null;/);
});
test('PostgreSQL email recovery: migration, concurrent workers, rollback and atomic session/challenge revocation',{skip:!process.env.ER_TEST_DATABASE_URL},async t=>{
 const u=new URL(process.env.ER_TEST_DATABASE_URL);assert.ok(['127.0.0.1','localhost'].includes(u.hostname)&&u.pathname.startsWith('/er_test_'));const admin=new Pool({connectionString:u.toString()}),schema='recovery_test_'+crypto.randomBytes(8).toString('hex');await admin.query('CREATE SCHEMA '+schema);const pool=new Pool({connectionString:u.toString(),options:'-c search_path='+schema}),p2=new Pool({connectionString:u.toString(),options:'-c search_path='+schema}),a=createStore({},pool),b=createStore({},p2);t.after(async()=>{await a.close();await b.close();await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.end();});await Promise.all([a.migrate(),b.migrate()]);
 const {h,session}=await setup(t,a),h2=await harness(t,enabled,'[]',b),customer=(await pool.query('SELECT * FROM er_customers')).rows[0];await pool.query("INSERT INTO er_customer_recovery(challenge_hash,customer_id,identity_hash,code_verifier,reset_hash,created_at,expires_at,verified_at,delivery_state) VALUES($1,$2,$1,$1,$1,now(),now()+interval '10 minutes',now(),'sent')",['1'.repeat(64),customer.id]);await Promise.all([a.migrate(),b.migrate()]);const legacy=(await pool.query("SELECT consumed_at,reset_hash FROM er_customer_recovery WHERE method='sms'")).rows[0];assert.ok(legacy.consumed_at);assert.equal(legacy.reset_hash,null);assert.equal(await a.recoveryGrant('1'.repeat(64),Date.now()),false);
 await Promise.all([sent(h),sent(h2)]);assert.equal(h.state.emailMessages.length+h2.state.emailMessages.length,1);const winner=h.state.emailMessages.length?h:h2,token=winner.state.emailMessages[0].token;for(let i=0;i<100;i++){if((await pool.query('SELECT delivery_state FROM er_customer_recovery WHERE email_token_hash=$1',[hashToken(token)])).rows[0].delivery_state==='sent')break;await new Promise(r=>setTimeout(r,5));}const row=(await pool.query('SELECT * FROM er_customer_recovery WHERE email_token_hash=$1',[hashToken(token)])).rows[0];assert.equal(row.code_verifier,null);assert.ok(!JSON.stringify(row).includes(token));const outcomes=await Promise.all([exchange(h,token),exchange(h2,token)]);assert.deepEqual(outcomes.map(r=>r.status).sort(),[200,400]);const grant=outcomes.find(r=>r.status===200),key=hashToken(resetCookie(grant).split('=')[1]);
 await pool.query("CREATE FUNCTION reject_test_session_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic rollback'; END $$; CREATE TRIGGER reject_test_session_delete BEFORE DELETE ON er_customer_sessions FOR EACH ROW EXECUTE FUNCTION reject_test_session_delete()");await assert.rejects(a.resetCustomerPassword(key,'synthetic replacement hash',Date.parse('2026-10-01T16:00:00Z')));assert.equal((await a.customerByEmail(customer.normalized_email)).password_hash,customer.password_hash);assert.equal(await a.recoveryGrant(key,Date.parse('2026-10-01T16:00:00Z')),true);await pool.query('DROP TRIGGER reject_test_session_delete ON er_customer_sessions; DROP FUNCTION reject_test_session_delete()');const results=await Promise.all([reset(h,grant),reset(h2,grant)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);assert.equal((await h2.request('/api/customer/profile',undefined,{cookie:session})).status,401);assert.ok((await pool.query('SELECT consumed_at FROM er_customer_recovery WHERE customer_id=$1',[customer.id])).rows.every(r=>r.consumed_at));const stale={hash:hashToken('synthetic stale session'),created:new Date(),expires:new Date(Date.now()+60000)};assert.equal(await b.createCustomerSession(customer.id,stale,customer.password_hash),false);assert.equal((await h2.request('/api/customer/login',{email:account.email,password:account.password})).status,401);assert.equal((await h2.request('/api/customer/login',{email:account.email,password:newPassword})).status,200);
});
